# Generated by Django 4.2.1 on 2023-05-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0005_customusermodel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='active',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
