# Generated by Django 4.2.1 on 2023-05-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0006_remove_customusermodel_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
