# Generated by Django 4.2.1 on 2023-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0007_remove_customusermodel_is_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
