# Generated by Django 4.2.1 on 2023-05-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0009_customusermodel_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='userId',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='updated_at',
        ),
    ]
