# Generated by Django 4.2.1 on 2023-05-27 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0010_rename_userid_customusermodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
