# Generated by Django 4.2.1 on 2023-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0011_customusermodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
