# Generated by Django 4.2.1 on 2023-05-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0012_customusermodel_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='status',
        ),
    ]
