# Generated by Django 4.2.1 on 2023-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0013_remove_customusermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
