# Generated by Django 4.2.1 on 2023-05-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_user'),
        ('playfairauth', '0014_customusermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
