# Generated by Django 4.2.1 on 2023-05-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0016_remove_customusermodel_company_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
    ]
