# Generated by Django 4.2.1 on 2023-05-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0017_alter_company_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
