# Generated by Django 4.2.1 on 2023-05-29 07:04

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_savedcompanies_logo'),
        ('playfairauth', '0019_alter_customusermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('address', models.CharField(max_length=100, null=True)),
                ('postalCode', models.CharField(max_length=10, null=True)),
                ('bio', ckeditor.fields.RichTextField(null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('country', models.JSONField(null=True)),
                ('city', models.JSONField(null=True)),
                ('state', models.JSONField(null=True)),
                ('website', models.URLField(null=True)),
                ('linkedIn', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('education_level', models.CharField(max_length=100, null=True)),
                ('rating', models.CharField(max_length=5, null=True)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('useEmailAsUser', models.BooleanField(default=False)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('education', models.JSONField(null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('isAgeVisible', models.BooleanField(default=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('allow_in_listings', models.BooleanField(default=False)),
                ('first_logged_in', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=16)),
                ('expected_salary', models.CharField(default=0, max_length=50)),
                ('current_salary', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_expected_salary_visible', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
