# Generated by Django 4.2.1 on 2023-05-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0020_customuserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserprofile',
            old_name='isAgeVisible',
            new_name='is_age_visible',
        ),
        migrations.RenameField(
            model_name='customuserprofile',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
