# Generated by Django 4.2.1 on 2023-06-02 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0024_rename_firstname_customuserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='current_salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='expected_salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
