# Generated by Django 4.2.1 on 2023-06-03 04:34

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0025_alter_customuserprofile_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
