# Generated by Django 4.2.1 on 2023-06-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0026_alter_customuserprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='education',
        ),
    ]
