# Generated by Django 4.2.1 on 2023-06-03 06:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0027_remove_customuserprofile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='education_level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='instagram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='linkedIn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
