# Generated by Django 4.2.1 on 2023-06-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0028_alter_customuserprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='education_level',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='instagram',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='linkedIn',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='postal_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='website',
            field=models.URLField(default='', null=True),
        ),
    ]
