# Generated by Django 4.2.1 on 2023-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0029_alter_customuserprofile_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
