# Generated by Django 4.2.1 on 2023-06-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0033_alter_customuserprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='forgot_password_token',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
