# Generated by Django 4.2.1 on 2023-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0034_customusermodel_forgot_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='forgot_password_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
