# Generated by Django 4.2.1 on 2023-06-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0035_customusermodel_forgot_password_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='forgot_password_token',
            field=models.CharField(editable=False, max_length=200, null=True, unique=True),
        ),
    ]
