# Generated by Django 4.2.1 on 2023-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0036_alter_customusermodel_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='experience',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='industry',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
