# Generated by Django 4.2.1 on 2023-06-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0037_alter_customuserprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
