# Generated by Django 4.2.1 on 2023-06-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0038_customuserprofile_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='stripe_bank_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='stripe_id_back',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='stripe_id_front',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='stripe_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
