# Generated by Django 4.2.1 on 2023-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0039_customuserprofile_stripe_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
