# Generated by Django 4.2.1 on 2023-07-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0040_customusermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='gig_verified',
            field=models.BooleanField(default=False),
        ),
    ]
