# Generated by Django 4.2.1 on 2023-07-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0041_customusermodel_gig_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
