# Generated by Django 4.2.1 on 2023-07-14 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0042_alter_customusermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractor',
                'db_table': 'contractor',
            },
        ),
    ]
