# Generated by Django 4.2.1 on 2023-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0043_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stripe_bank_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stripe_id_back',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stripe_id_front',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stripe_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
