# Generated by Django 4.2.1 on 2023-07-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0046_alter_contractor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='country_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='country',
            field=models.CharField(null=True),
        ),
    ]
