# Generated by Django 4.2.1 on 2023-07-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0049_alter_customuserprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
