# Generated by Django 4.2.1 on 2023-07-18 05:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0050_alter_customuserprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
