# Generated by Django 4.2.1 on 2023-07-25 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0054_alter_customuserprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
