# Generated by Django 4.2.1 on 2023-07-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0055_alter_customuserprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
