# Generated by Django 4.2.1 on 2023-07-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0056_contractor_account_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='account_last_4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
