# Generated by Django 4.2.1 on 2023-07-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0057_contractor_account_last_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
