# Generated by Django 4.2.1 on 2023-07-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0058_contractor_lat_contractor_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
