# Generated by Django 4.2.1 on 2023-08-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0059_customusermodel_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='skills',
        ),
    ]
