# Generated by Django 4.2.1 on 2023-07-05 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_city_alter_contract_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
