# Generated by Django 4.2.1 on 2023-07-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_buyer_alter_contract_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='items',
        ),
    ]
