# Generated by Django 4.2.1 on 2023-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_contract_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], default='buying', max_length=100),
        ),
    ]
