# Generated by Django 4.2.1 on 2023-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='min_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=255, null=True),
        ),
    ]
