# Generated by Django 4.2.1 on 2023-07-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_contract_amount_alter_contract_max_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
