# Generated by Django 4.2.1 on 2023-07-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='user_type',
            field=models.CharField(default='company', max_length=100),
        ),
    ]
