# Generated by Django 4.2.1 on 2023-07-15 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0012_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
