# Generated by Django 4.2.1 on 2023-07-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_alter_contract_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10),
        ),
    ]
