# Generated by Django 4.2.1 on 2023-07-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='buyer',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='seller',
            new_name='poster',
        ),
    ]
