# Generated by Django 4.2.1 on 2023-07-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_rename_buyer_contract_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
    ]
