# Generated by Django 4.2.1 on 2023-07-16 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_alter_contract_contractor_alter_contract_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='candidates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), blank=True, null=True, size=None),
        ),
    ]
