# Generated by Django 4.2.1 on 2023-07-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_contract_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
    ]
