# Generated by Django 4.2.1 on 2023-07-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_remove_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], default='buying', max_length=100),
        ),
    ]
