# Generated by Django 4.2.1 on 2023-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_alter_contract_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
