# Generated by Django 4.2.1 on 2023-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_alter_contract_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('pending', 'Pending'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
