# Generated by Django 4.2.1 on 2023-07-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Cancelled', 'Cancelled'), ('Error', 'Error'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Paid', 'Paid'), ('In Progress', 'In Progress')], default='pending', max_length=20),
        ),
    ]
