# Generated by Django 4.2.1 on 2023-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Paid', 'Paid'), ('In Progress', 'Progress')], default='available', max_length=20),
        ),
    ]
