# Generated by Django 4.2.1 on 2023-08-24 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=''), blank=True, default=list, size=None),
        ),
    ]
