# Generated by Django 4.2.1 on 2023-08-25 01:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_contract_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('preview', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_image', to='contract.contract')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
