# Generated by Django 4.2.1 on 2023-08-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='images',
        ),
    ]
