# Generated by Django 4.2.1 on 2023-08-25 02:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_remove_contract_image_remove_contract_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=''), blank=True, default=list, size=None),
        ),
    ]
