# Generated by Django 4.2.1 on 2023-07-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeIntent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('object', models.CharField(blank=True, max_length=50)),
                ('amount', models.IntegerField(blank=True)),
                ('amount_capturable', models.IntegerField(blank=True)),
                ('amount_received', models.IntegerField(blank=True)),
                ('capture_method', models.CharField(blank=True, max_length=20)),
                ('client_secret', models.CharField(blank=True, max_length=100)),
                ('confirmation_method', models.CharField(blank=True, max_length=20)),
                ('created', models.BigIntegerField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('livemode', models.BooleanField(blank=True, default=False)),
                ('next_action', models.JSONField(blank=True, null=True)),
                ('payment_method_types', models.JSONField(blank=True)),
                ('receipt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('statement_descriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('statement_descriptor_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('transfer_data', models.JSONField(blank=True, null=True)),
                ('transfer_group', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_details', models.JSONField(blank=True, default=dict)),
                ('application_fee_amount', models.IntegerField(blank=True, null=True)),
                ('automatic_payment_methods', models.JSONField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment_method_options', models.JSONField(blank=True, null=True)),
                ('processing', models.JSONField(blank=True, null=True)),
                ('setup_future_usage', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
