# Generated by Django 4.2.1 on 2023-07-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0029_alter_appliedcontract_amount'),
        ('payment', '0002_stripeintent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeIntent',
            new_name='PaymentIntent',
        ),
    ]
