# Generated by Django 4.2.1 on 2023-06-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='delivery_type',
            new_name='delivery_type',
        ),
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('error', 'Error'), ('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10),
        ),
    ]
