# Generated by Django 4.2.1 on 2023-07-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_rename_deliverytype_gig_delivery_type_gig_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gig',
            table='gig',
        ),
    ]
