# Generated by Django 4.2.1 on 2023-07-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_alter_gig_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gig',
            table=None,
        ),
    ]
