# Generated by Django 4.2.1 on 2023-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmember',
            name='online',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
