# Generated by Django 4.2.1 on 2023-07-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_buyer_alter_contract_seller'),
        ('chat', '0006_remove_conversationmember_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_contract', to='contract.contract'),
        ),
    ]
