# Generated by Django 4.2.1 on 2023-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(blank=True, null=True),
        ),
    ]
