# Generated by Django 4.2.1 on 2023-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(null=True),
        ),
    ]
