# Generated by Django 4.2.1 on 2023-07-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_alter_appliedcontract_is_approved'),
        ('chat', '0016_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='applied_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_contract', to='candidate.appliedcontract'),
        ),
    ]
