# Generated by Django 4.2.1 on 2023-08-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_alter_appliedcontract_payment_intent'),
        ('chat', '0017_conversation_applied_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='applied_contract',
        ),
        migrations.AddField(
            model_name='conversation',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='candidate.appliedcontract'),
        ),
    ]
