# Generated by Django 4.2.1 on 2023-05-31 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_delete_candidatessavedjobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedJobs',
            new_name='SavedJob',
        ),
    ]
