# Generated by Django 4.2.1 on 2023-05-31 06:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_delete_candidatesapplied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_rename_createdat_company_created_date_and_more'),
        ('candidate', '0002_rename_savedjobs_savedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=3000)),
                ('appliedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('coverLetter', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('isApproved', models.BooleanField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
