# Generated by Django 4.2.1 on 2023-06-01 02:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_savedcopmany'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedCopmany',
            new_name='SavedCompany',
        ),
    ]
