# Generated by Django 4.2.1 on 2023-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_rename_savedcopmany_savedcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
