# Generated by Django 4.2.1 on 2023-06-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0024_rename_firstname_customuserprofile_first_name_and_more'),
        ('candidate', '0007_alter_appliedjob_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playfairauth.customuserprofile'),
        ),
    ]
