# Generated by Django 4.2.1 on 2023-06-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_appliedjob_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='userprofile',
        ),
    ]
