# Generated by Django 4.2.1 on 2023-06-02 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_remove_appliedjob_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
