# Generated by Django 4.2.1 on 2023-06-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_appliedjob_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='isApproved',
            new_name='is_approved',
        ),
    ]
