# Generated by Django 4.2.1 on 2023-06-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0033_alter_customuserprofile_logo'),
        ('candidate', '0011_rename_isapproved_appliedjob_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playfairauth.customuserprofile'),
        ),
    ]
