# Generated by Django 4.2.1 on 2023-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_remove_appliedjob_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='userprofile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
