# Generated by Django 4.2.1 on 2023-07-14 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0015_remove_appliedjob_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='createdAt',
            new_name='created_date',
        ),
        migrations.CreateModel(
            name='SavedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(auto_created=True, default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
