# Generated by Django 4.2.1 on 2023-07-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0047_customuserprofile_country_code_and_more'),
        ('candidate', '0017_appliedcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedcontract',
            name='user',
        ),
        migrations.AddField(
            model_name='appliedcontract',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playfairauth.contractor'),
        ),
    ]
