# Generated by Django 4.2.1 on 2023-07-15 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_remove_appliedcontract_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontract',
            name='coverLetter',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
