# Generated by Django 4.2.1 on 2023-07-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_appliedcontract_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appliedcontract',
            table='applied_contract',
        ),
    ]
