# Generated by Django 4.2.1 on 2023-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_alter_appliedcontract_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontract',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
