# Generated by Django 4.2.1 on 2023-07-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_alter_appliedcontract_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
