# Generated by Django 4.2.1 on 2023-07-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0029_alter_appliedcontract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontract',
            name='payment_intent',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
