# Generated by Django 4.2.1 on 2023-07-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0030_alter_appliedcontract_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='paid',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
