# Generated by Django 4.2.1 on 2023-07-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0031_appliedjob_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontract',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appliedcontract',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Cancelled', 'Cancelled'), ('Error', 'Error'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Paid', 'Paid'), ('In Progress', 'In Progress')], default='pending', max_length=20),
        ),
    ]
