# Generated by Django 4.2.1 on 2023-08-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_appliedcontract_paid_appliedcontract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontract',
            name='payment_intent',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
