# Generated by Django 4.2.1 on 2023-05-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playfairauth', '0016_remove_customusermodel_company_company'),
        ('company', '0002_remove_company_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
