# Generated by Django 4.2.1 on 2023-05-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
