# Generated by Django 4.2.1 on 2023-06-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
