# Generated by Django 4.2.1 on 2023-06-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
