# Generated by Django 4.2.1 on 2023-06-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
