# Generated by Django 4.2.1 on 2023-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_company_city_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
