# Generated by Django 4.2.1 on 2023-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
