# Generated by Django 4.2.1 on 2023-06-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_company_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_bank_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
