# Generated by Django 4.2.1 on 2023-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_company_stripe_bank_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
