# Generated by Django 4.2.1 on 2023-06-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_company_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_person',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
