# Generated by Django 4.2.1 on 2023-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_stripe_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stripe_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
