# Generated by Django 4.2.1 on 2023-06-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_alter_company_stripe_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_id_back',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_id_front',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
