# Generated by Django 4.2.1 on 2023-07-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_stripe_id_back_company_stripe_id_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
