# Generated by Django 4.2.1 on 2023-07-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founded_in',
            field=models.IntegerField(default=2023, max_length=5, null=True),
        ),
    ]
