# Generated by Django 4.2.1 on 2023-05-29 05:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_twitter',
            new_name='twitter',
        ),
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
