# Generated by Django 4.2.1 on 2023-05-29 05:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_iscommision_job_iscommission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='appliedCount',
            new_name='applied_count',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='isCommission',
            new_name='is_commission',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='maxSalary',
            new_name='max_salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='minSalary',
            new_name='min_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobType',
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
