# Generated by Django 4.2.1 on 2023-05-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_appliedcount_job_applied_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesapplied',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='createdAt',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='isRemote',
            new_name='is_remote',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='startAt',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='weeklyHours',
            new_name='weekly_hours',
        ),
    ]
