# Generated by Django 4.2.1 on 2023-05-31 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_isactive_candidatesapplied_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=[], null=True, size=None),
        ),
    ]
