# Generated by Django 4.2.1 on 2023-05-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatesSavedJobs',
        ),
    ]
