# Generated by Django 4.2.1 on 2023-05-31 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_delete_candidatesapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
