# Generated by Django 4.2.1 on 2023-06-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='expiredAt',
            new_name='expired_at',
        ),
    ]
