# Generated by Django 4.2.1 on 2023-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_city_alter_job_country_alter_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('Business', 'Business'), ('Software', 'Software'), ('Automotive', 'Automotive'), ('Finance', 'Finance'), ('Education/Training', 'Education'), ('Telecommunication', 'Telecommunication'), ('Agriculture', 'Agriculture'), ('Graphics', 'Graphics'), ('Digital Marketing', 'Digitalmarketing'), ('Design', 'Design'), ('Video', 'Video'), ('Animation', 'Animation'), ('Audio', 'Audio'), ('Photography', 'Photography'), ('Writing', 'Writing'), ('Human Resources', 'Humanresources'), ('Legal', 'Legal'), ('Security', 'Security'), ('Health & Beauty', 'Healthybeauty')], default='Business', max_length=100),
        ),
    ]
