# Generated by Django 4.2.1 on 2023-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Advertising', 'Advertising'), ('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Automative', 'Automative'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Business', 'Business'), ('Business Development', 'Businessdevelopment'), ('Chemical', 'Chemical'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Consumer Services', 'Consumerservices'), ('Customer Service', 'Customerservice'), ('Data Entry', 'Dataentry'), ('Design', 'Design'), ('Education', 'Education'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Environmental', 'Environmental'), ('Event Planning', 'Eventplanning'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Food Services', 'Foodservices'), ('Gaming', 'Gaming'), ('Government', 'Government'), ('Graphics', 'Graphics'), ('Health & Beauty', 'Healthbeauty'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Human Resources', 'Humanresources'), ('Information Technology', 'Informationtechnology'), ('Insurance', 'Insurance'), ('Interior Design', 'Interiordesign'), ('Investment', 'Investment'), ('Journalism', 'Journalism'), ('Legal', 'Legal'), ('Legal Services', 'Legalservices'), ('Logistics', 'Logistics'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Media', 'Media'), ('Military', 'Military'), ('Music', 'Music'), ('Nonprofit', 'Nonprofit'), ('Operations', 'Operations'), ('Pharmaceutical', 'Pharmaceutical'), ('Photography', 'Photography'), ('Product Management', 'Productmanagement'), ('Project Management', 'Projectmanagement'), ('Public Health', 'Publichealth'), ('Public Relations', 'Publicrelations'), ('Quality Assurance', 'Qualityassurance'), ('Real Estate', 'Realestate'), ('Research', 'Research'), ('Restaurant', 'Restaurant'), ('Retail', 'Retail'), ('Sales', 'Sales'), ('Science', 'Science'), ('Security', 'Security'), ('Social Services', 'Socialservices'), ('Software', 'Software'), ('Sports', 'Sports'), ('Supply Chain', 'Supplychain'), ('Telecommunications', 'Telecommunications'), ('Tourism', 'Tourism'), ('Training', 'Training'), ('Transportation', 'Transportation'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Video', 'Video'), ('Wealth Management', 'Wealthmanagement'), ('Writing & Translation', 'Writingtranslation')], default='Business', max_length=100),
        ),
    ]
