# Generated by Django 4.2.1 on 2023-06-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_stripe_id_back_company_stripe_id_front'),
        ('job', '0016_alter_job_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company'),
        ),
    ]
