# Generated by Django 4.2.1 on 2023-07-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_job_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rate_type',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Hourly', 'Hourly')], default='Salary', max_length=100),
        ),
    ]
