# Generated by Django 4.2.1 on 2023-08-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_job_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(default='Sales', max_length=100, null=True),
        ),
    ]
