# Generated by Django 4.2.1 on 2023-08-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_alter_job_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
