name: Playfair CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: login
      uses: actions/heroku@main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: set remote
      run: git remote set-url origin https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/playfair-production.git
    - name: push and deploy
      run: git push origin HEAD:master -f

# name: Playfair Tests

# on:
#   push:
#     branches:
#       - main
  
#   pull_request:
#     branches:
#       - main

# # on:
# #   schedule:
# #     - cron:  '*/15 * * * *'

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.7
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.7
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Coverage report
#       run: |
#         pip install coverage
#         coverage run manage.py test
#         coverage report
#     - name: Django Testing
#       run: |
#         python3 manage.py test